language: objective-c

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8


before_install:
    - env
    - locale
#    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
#    - pod --version
#    - pod setup --silent > /dev/null
#    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script: 
   - set -o pipefail

   - echo Build as framework
   - xcodebuild clean build -workspace QPDialCodePickerView.xcworkspace -scheme QPDialCodePickerView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

   - echo Run test
   - xcodebuild test -workspace QPDialCodePickerView.xcworkspace -scheme QPDialCodePickerView -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES  | xcpretty -c

after_success:
    - bash <(curl -s https://codecov.io/bash) 
